### ISSUE TITLE
Add a UI test for the Showcase (OSOE-78)

### ISSUE THREAD

**Issue by Piedone** [Lombiq/Orchard-UIKit#8]
Add a UI test extension method and a corresponding test in OSOCE that opens the Showcase page and plays around with it a bit.

**Comment by BanzragchUchral** [comment]
How many or what kind of tests do you want here?

**Comment by Piedone** [comment]
I'd like the kind of test "that opens the Showcase page and plays around with it a bit" ;). This can be a single UI test with multiple operations and assertions. Note that we have this Showcase page implemented in a feature: https://github.com/Lombiq/Orchard-UIKit#documentation
